services:
  - type: web
    name: marketing-analytics-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pullRequestPreviewsEnabled: false
