import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Download, ExternalLink, FileText, Presentation, RotateCcw, ShieldCheck } from "lucide-react";
import { PresentationApp } from "./presentation/PresentationApp";
import { numberValue, SECTION_LABELS, textValue, type DashboardData, type DataRow } from "./types";

const redirects: Record<string, string> = { "s-essential": "s-summary", "s-exec": "s-summary", "s-channel": "s-channels", "s-creative": "s-content", "s-attrib": "s-attribution", "s-segment": "s-audience", "s-budget": "s-strategy", "s-conclusion": "s-strategy", "s-advanced": "s-evidence", "s-appendix": "s-evidence" };
const money = (n: number) => n ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(n) : "Unavailable";
const percent = (n: number) => Number.isFinite(n) ? `${(n * 100).toFixed(1)}%` : "Unavailable";
const clean = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function downloadCsv(rows: DataRow[], filename: string) { const keys = [...new Set(rows.flatMap(Object.keys))]; const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const body = [keys.map(quote).join(","), ...rows.map((row) => keys.map((key) => quote(row[key])).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([body], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = `${filename}.csv`; link.click(); URL.revokeObjectURL(url); }

function Bars({ rows, label, value, format = (n: number) => n.toLocaleString() }: { rows: DataRow[]; label: string; value: string; format?: (n: number) => string }) { const shown = rows.slice(0, 8); const max = Math.max(1, ...shown.map((row) => Math.abs(numberValue(row, value)))); return <div className="bars">{shown.map((row, index) => { const n = numberValue(row, value); return <div className="bar-row" key={`${textValue(row, label)}-${index}`}><span>{clean(textValue(row, label, "Unknown"))}</span><div><i style={{ width: `${Math.max(2, Math.abs(n) / max * 100)}%` }} /></div><b>{format(n)}</b></div>; })}</div>; }

function DataTable({ rows, columns, exportName }: { rows: DataRow[]; columns: Array<[string, string]>; exportName: string }) { const [sort, setSort] = useState<string>(columns[0]?.[0] || ""); const ordered = [...rows].sort((a, b) => typeof a[sort] === "number" ? numberValue(b, sort) - numberValue(a, sort) : textValue(a, sort).localeCompare(textValue(b, sort))); return <div className="data-table"><button className="csv" onClick={() => downloadCsv(ordered, exportName)}><Download /> CSV</button><div className="table-scroll"><table><thead><tr>{columns.map(([key, title]) => <th key={key}><button onClick={() => setSort(key)}>{title}</button></th>)}</tr></thead><tbody>{ordered.slice(0, 24).map((row, index) => <tr key={index}>{columns.map(([key]) => <td key={key}>{typeof row[key] === "number" ? (key.includes("rate") || key.includes("share") || key === "ctr" ? percent(numberValue(row, key)) : key.includes("amount") || key.includes("spend") || key.includes("pipeline") ? money(numberValue(row, key)) : numberValue(row, key).toLocaleString()) : textValue(row, key, "—")}</td>)}</tr>)}</tbody></table></div></div>; }

function DatasetCard({ title, rows, note, children }: { title: string; rows: DataRow[]; note?: string; children: React.ReactNode }) { return <section className="dataset-card"><div className="card-heading"><div><h3>{title}</h3>{note && <p>{note}</p>}</div></div>{rows.length ? children : <p className="unavailable">Unavailable for this source snapshot.</p>}</section>; }

function Dashboard({ data, section }: { data: DashboardData; section: string }) {
  const d = data.datasets; const summary = d.summary?.[0]; const findings = data.findings;
  if (section === "s-summary") return <><section className="hero"><p className="eyebrow">CMO DECISION BRIEF · EVIDENCE FIRST</p><h1>Measure the channels. Test the creative. Stop mistaking touchpoints for proof.</h1><p>Which marketing channels and content formats support acquisition, recorded revenue, and engagement—and how should the CMO change strategy?</p><div className="hero-actions"><a className="primary" href="#present/main-01"><Presentation /> Present findings <ArrowRight /></a><a href="#s-evidence">Review methods</a></div></section><section className="metric-strip"><div><span>ANALYTICAL POPULATION</span><b>{numberValue(summary, "opportunities").toLocaleString()}</b><small>non-deleted CRM snapshots</small></div><div><span>RECORDED PIPELINE</span><b>{money(numberValue(summary, "recorded_pipeline"))}</b><small>source-recorded amount</small></div><div><span>RESOLVED WIN RATE</span><b>{percent(numberValue(summary, "won") / Math.max(1, numberValue(summary, "resolved")))}</b><small>won / resolved</small></div><div><span>TOUCH-LINKED, 365D</span><b>{percent(numberValue(summary, "linked_share"))}</b><small>2024 marketing windows constrain coverage</small></div></section><section className="findings-grid">{findings.slice(0, 3).map((finding) => <article key={finding.id}><span className={`status ${finding.evidence_status.toLowerCase()}`}>{finding.evidence_status}</span><h2>{finding.headline}</h2><p>{finding.summary}</p><small>{finding.caveats[0]}</small></article>)}</section><ActionPlan data={data} /></>;
  if (section === "s-channels") { const rows = d.channel_scorecard.filter((row) => row.scope === "All history" && row.business_motion === "All"); return <><PageTitle title="Channel effectiveness" text="A descriptive scorecard, not an opaque winner-take-all model. Choose actions from resolved outcomes, recorded amounts, sample size, and available spend coverage." /><div className="two-up"><DatasetCard title="Recorded won amount" rows={rows} note="All CRM history · non-deleted snapshots"><Bars rows={rows} label="channel" value="recorded_won_amount" format={money} /></DatasetCard><DatasetCard title="Resolved win rate" rows={rows} note="Wilson interval is carried in the table"><Bars rows={rows} label="channel" value="win_rate" format={percent} /></DatasetCard></div><DataTable rows={rows} exportName="channel-scorecard" columns={[["channel", "Channel"], ["opportunities", "Opps"], ["resolved", "Resolved"], ["win_rate", "Win rate"], ["recorded_won_amount", "Recorded won"], ["tracked_spend", "Tracked spend"], ["evidence_status", "Evidence"]]} /></> }
  if (section === "s-content") return <><PageTitle title="Content & engagement" text="Advertising, email, and website evidence use different denominators. These measures should not be combined into one funnel." /><div className="three-up"><DatasetCard title="Advertising · top eligible ads" rows={d.ad_rankings} note="CTR is weighted clicks / impressions; rank within platform"><Bars rows={d.ad_rankings} label="ad_id" value="ctr" format={percent} /></DatasetCard><DatasetCard title="Email · unique clickers" rows={d.email_content} note="Conditional on appearing in engagement logs"><Bars rows={d.email_content} label="content_title" value="unique_clickers" /></DatasetCard><DatasetCard title="Website · recordings" rows={d.web_content} note="Contact-page flags are observed activity, not confirmed acquisition"><Bars rows={d.web_content} label="page_group" value="unique_recordings" /></DatasetCard></div><DatasetCard title="Creative bundles, not independent effects" rows={d.creative_bundles} note={data.dataset_status.creative_bundles?.reason}><DataTable rows={d.creative_bundles} exportName="creative-bundles" columns={[["bundle", "Observed bundle"], ["distinct_ads", "Ads"], ["impressions", "Impressions"], ["clicks", "Clicks"], ["ctr", "CTR"], ["evidence_status", "Status"]]} /></DatasetCard></>;
  if (section === "s-attribution") return <><PageTitle title="Attribution & journeys" text="Source flags and linked pre-opportunity touches are intentionally shown as exclusive groups. Neither establishes incremental causality." /><div className="two-up"><DatasetCard title="Source / touch overlap" rows={d.attribution_overlap}><Bars rows={d.attribution_overlap} label="group" value="opportunities" /></DatasetCard><DatasetCard title="Model sensitivity" rows={d.attribution_model_sensitivity} note={data.dataset_status.attribution_model_sensitivity?.reason}><Bars rows={d.attribution_model_sensitivity} label="channel" value="attributed_amount" format={money} /></DatasetCard></div><DataTable rows={d.journey_outcomes} exportName="journey-outcomes" columns={[["sequence", "Linked sequence"], ["resolved", "Resolved"], ["wins", "Wins"], ["win_rate", "Win rate"], ["linked_population_share", "Linked share"]]} /></>;
  if (section === "s-trends") return <><PageTitle title="Trends & conversion" text="The historical CRM trend is broader than marketing logs. Conversion decomposition reports percentage-point contributions, not causal diagnosis." /><div className="two-up"><DatasetCard title="Quarterly CRM outcomes" rows={d.channel_trends}><Bars rows={d.channel_trends} label="quarter" value="win_rate" format={percent} /></DatasetCard><DatasetCard title="2022 H1 → 2024 H1 decomposition" rows={d.conversion_decomposition}><Bars rows={d.conversion_decomposition} label="stratum" value="contribution_pp" format={(n) => `${n.toFixed(1)} pp`} /></DatasetCard></div></>;
  if (section === "s-audience") return <><PageTitle title="Target audience" text="Eligibility is domain-level. Any customer or active-pipeline conflict excludes the domain; profile conflicts are sent to review rather than ranked." /><div className="two-up"><DatasetCard title="Eligibility exclusion path" rows={d.audience_exclusions}><Bars rows={d.audience_exclusions} label="stage" value="domains" /></DatasetCard><DatasetCard title="Eligible current domains" rows={d.audience_priority} note="Shortlist requires ≥30 resolved historical opportunities"><Bars rows={d.audience_priority} label="segment_fit" value="eligible_domains" /></DatasetCard></div><DataTable rows={d.audience_priority} exportName="audience-priority" columns={[["segment_fit", "Segment / fit"], ["resolved", "Resolved"], ["win_rate", "Win rate"], ["wilson_low", "Wilson lower"], ["eligible_domains", "Eligible domains"], ["status", "Status"]]} /></>;
  if (section === "s-strategy") return <><PageTitle title="Strategy & experiments" text="Historical spend is a reference. The proposed 90-day account experiment uses a randomized holdout and requires feasible enrollment." /><ActionPlan data={data} /><DatasetCard title="Power scenarios" rows={d.experiment_scenarios} note="5% baseline and 2-point lift are planning assumptions"><DataTable rows={d.experiment_scenarios} exportName="experiment-scenarios" columns={[["scenario", "Scenario"], ["baseline_rate", "Baseline"], ["absolute_lift", "Absolute lift"], ["required_total", "Required total"], ["eligible_audience", "Eligible audience"], ["feasibility", "Feasibility"]]} /></DatasetCard></>;
  return <><PageTitle title="Evidence & methods" text="A durable record of the analytical population, observation windows, definitions, and limitations behind every decision." /><div className="two-up"><DatasetCard title="Population reconciliation" rows={d.population_reconciliation}><DataTable rows={d.population_reconciliation} exportName="population-reconciliation" columns={[["stage", "Stage"], ["opportunities", "Opportunities"], ["recorded_amount", "Recorded amount"], ["won_opportunities", "Wins"]]} /></DatasetCard><DatasetCard title="Source coverage" rows={d.source_coverage}><DataTable rows={d.source_coverage} exportName="source-coverage" columns={[["source", "Source"], ["min_timestamp", "First observed"], ["max_timestamp", "Last observed"], ["usable_touchpoints", "Usable touches"]]} /></DatasetCard></div><section className="definitions"><h2>Metric definitions</h2>{Object.entries(data.metric_definitions).map(([key, value]) => <p key={key}><b>{clean(key)}.</b> {value}</p>)}</section></>;
}

function PageTitle({ title, text }: { title: string; text: string }) { return <header className="page-title"><p className="eyebrow">CMO DECISION LAYER</p><h1>{title}</h1><p>{text}</p></header>; }
function ActionPlan({ data }: { data: DashboardData }) { return <section className="action-plan"><div className="action-heading"><span className="eyebrow">DECISION REGISTER</span><h2>Make next steps measurable</h2></div>{data.recommendations.map((item) => <article key={item.id}><span className="status observed">{item.confidence_status}</span><h3>{item.decision}</h3><p>{item.immediate_next_step}</p><small><b>Measure:</b> {item.primary_success_measure}</small><small><b>Rule:</b> {item.scale_stop_rule}</small></article>)}</section>; }

export default function App() {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); const [hash, setHash] = useState(location.hash.replace("#", "") || "s-summary");
  const load = () => fetch("./dashboard-data.json", { cache: "no-store" }).then((response) => { if (!response.ok) throw new Error(`Data request failed (${response.status})`); return response.json(); }).then((payload: DashboardData) => { if (payload.schema_version !== 3) throw new Error("The analytical contract is not schema version 3."); setData(payload); setError(""); }).catch((reason) => setError(reason.message));
  useEffect(() => { load(); const listener = () => setHash(location.hash.replace("#", "") || "s-summary"); addEventListener("hashchange", listener); return () => removeEventListener("hashchange", listener); }, []);
  if (error) return <main className="load-state"><ShieldCheck /><h1>Evidence file unavailable</h1><p>{error}</p><button className="primary" onClick={load}><RotateCcw /> Retry</button></main>;
  if (!data) return <main className="load-state"><span className="loading-dot" /> Loading verified evidence…</main>;
  if (hash.startsWith("presenter/")) return <PresentationApp data={data} presenter />;
  if (hash.startsWith("present/")) return <PresentationApp data={data} />;
  const section = redirects[hash] || (SECTION_LABELS[hash] ? hash : "s-summary"); if (section !== hash) history.replaceState(null, "", `#${section}`);
  return <main className="app-shell"><aside className="sidebar"><a href="#s-summary" className="brand">NORTH<span>STAR</span><small>CMO DECISION SYSTEM</small></a><nav>{Object.entries(SECTION_LABELS).map(([id, label], index) => <a key={id} className={section === id ? "active" : ""} href={`#${id}`}><i>{String(index + 1).padStart(2, "0")}</i>{label}</a>)}</nav><div className="sidebar-footer"><span>STATIC SNAPSHOT</span><b>{data.meta.snapshot_id}</b><a href={data.manifest.legacy_archive} target="_blank"><ExternalLink /> Historical archive</a></div></aside><div className="mobile-nav"><a className="brand" href="#s-summary">NORTH<span>STAR</span></a><select value={section} onChange={(event) => location.hash = event.target.value}>{Object.entries(SECTION_LABELS).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></div><section className="workbench"><header className="topbar"><div><span>CASE STUDY / MARKETING EFFECTIVENESS</span><b>{data.meta.period}</b></div><div><button onClick={() => window.print()}><FileText /> Print</button><a className="present-link" href="#present/main-01"><Presentation /> Present findings</a></div></header><Dashboard data={data} section={section} /><footer className="dashboard-footer">Snapshot {data.meta.snapshot_id} · {data.meta.method_version} · generated {new Date(data.meta.generated_at).toLocaleDateString()} · Recorded amounts are source values, not confirmed recognized revenue.</footer></section></main>;
}
